# Generated by Django 4.1.6 on 2023-03-15 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shorthand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AnswerTest1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField()),
                ('text', models.CharField(max_length=255, null=True)),
                ('audioNoise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Test.noise')),
                ('audioShorthand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Test.shorthand')),
            ],
        ),
    ]
