# Generated by Django 4.1.6 on 2023-03-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_alter_answertest1_audioshorthand'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertest1',
            name='correct',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
