# Generated by Django 4.1.6 on 2023-03-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0006_alter_answersnoise_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noise',
            name='text',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='shorthand',
            name='text',
            field=models.FileField(upload_to=''),
        ),
    ]
