# Generated by Django 4.1.6 on 2023-03-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0007_alter_noise_text_alter_shorthand_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noise',
            name='audio',
            field=models.FileField(upload_to='noise_audio/'),
        ),
        migrations.AlterField(
            model_name='noise',
            name='text',
            field=models.FileField(upload_to='noise_csv/'),
        ),
        migrations.AlterField(
            model_name='shorthand',
            name='audio',
            field=models.FileField(upload_to='shorthand_audio/'),
        ),
        migrations.AlterField(
            model_name='shorthand',
            name='text',
            field=models.FileField(upload_to='shorthand_csv/'),
        ),
    ]
