# Generated by Django 4.1.6 on 2023-03-15 20:48

import Test.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0008_alter_noise_audio_alter_noise_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noise',
            name='audio',
            field=models.FileField(upload_to=Test.models.PathAndRename('noise/')),
        ),
    ]
